import {githubRequest,compareLayouts} from './city-storage.mjs';
import {capacity,planRacks,calibrateBackground} from './city-design.mjs';

import * as THREE from 'three';
import {loadAssets,fitAsset,rackAsset,animateWorker,releaseInstance,assetInfo,cacheStats} from './city-assets.mjs';
import {RoomEnvironment} from './vendor/addons/environments/RoomEnvironment.js';
import {thumbnail} from './city-thumbnails.mjs';
import {Logistics,qualityDemo,STEP} from './city-logistics.mjs';
import {toWorld,rotationRadians} from './city-coordinates.mjs';
await loadAssets();
import {rackRenderPlan,rackParts} from './city-render.mjs';
let rackPlan={compact:false,estimatedParts:0,racks:0};
import {OrbitControls} from './vendor/OrbitControls.js';
import {CATALOG,MAX_OBJECTS,copy,clamp,uid,object,normalize,demo,solid,footprint,placementError,blocked,Simulation,History,utf8base64,fromBase64,repoPath} from './city-core.mjs';
const $=id=>document.getElementById(id), KEY='warehouse-city-v9', OLD='warehouse-studio-project-v1';
let layout, loadWarning='',autosaveBlocked=false;let operationKind='cycle',simAccumulator=0;const cargoGroups=new Map();
try{const saved=localStorage.getItem(KEY);if(saved&&!localStorage.getItem(KEY+'-before-renewal'))localStorage.setItem(KEY+'-before-renewal',saved);layout=saved?normalize(JSON.parse(saved)):demo();}catch(e){try{const original=localStorage.getItem(KEY);if(original)localStorage.setItem(KEY+'-recovery-'+Date.now(),original);}catch{}autosaveBlocked=true;layout=demo();loadWarning='저장 도면을 읽지 못했습니다. 기존 데이터는 보존했습니다. '+e.message;}
let history=new History(layout),mode='edit',selected=null,tool=null,rotation=0,brush=null,ghost=null,drag=null,pointerDown=null,sim=null,playing=false,dirtyTimer=0,grid=null,selectionBox=null,topView=false,reviewCount=0;
const multiSelected=new Set();let scenarioA=null,experimentWorker=null;const keys=new Set(),groups=new Map(),simGroups=new Map();
const shellRoot=new THREE.Group(),labelRoot=new THREE.Group();
let yaw=0,pitch=0,walk={x:18,y:22},savedView=null,lastTime=performance.now(),uiTimer=0;
const scene=new THREE.Scene();scene.background=new THREE.Color('#dfe9ed');scene.fog=new THREE.Fog('#dfe9ed',160,500);
const renderer=new THREE.WebGLRenderer({canvas:$('scene'),antialias:true,preserveDrawingBuffer:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=new URLSearchParams(location.search).get('quality')!=='low';renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const perspective=new THREE.PerspectiveCamera(48,1,.05,800),orthographic=new THREE.OrthographicCamera(-30,30,20,-20,.05,800);let camera=perspective;const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.485;controls.minDistance=3;controls.maxDistance=350;controls.mouseButtons={LEFT:THREE.MOUSE.PAN,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.ROTATE};
scene.add(new THREE.HemisphereLight(0xffffff,0x8ba0aa,1.35));const sun=new THREE.DirectionalLight(0xffffff,2.3);sun.position.set(30,60,15);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-60;sun.shadow.camera.right=60;sun.shadow.camera.top=60;sun.shadow.camera.bottom=-60;sun.shadow.camera.far=200;sun.shadow.normalBias=.035;scene.add(sun);
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const pmrem=new THREE.PMREMGenerator(renderer),roomEnvironment=new RoomEnvironment();const environment=pmrem.fromScene(roomEnvironment,.04);scene.environment=environment.texture;scene.environmentIntensity=.35;roomEnvironment.dispose();pmrem.dispose();
const objectsRoot=new THREE.Group(),groundRoot=new THREE.Group(),agentRoot=new THREE.Group(),pathRoot=new THREE.Group();scene.add(objectsRoot,groundRoot,agentRoot,pathRoot,shellRoot,labelRoot);
const textureLoader=new THREE.TextureLoader();const floorMaterial=new THREE.MeshStandardMaterial({color:'#d7d9da',roughness:.65});for(const [suffix,slot]of [['albedo','map'],['normal','normalMap'],['roughness','roughnessMap']]){const t=textureLoader.load('./assets/textures/epoxy-'+suffix+'.png');t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(20,20);if(suffix==='albedo')t.colorSpace=THREE.SRGBColorSpace;floorMaterial[slot]=t;}floorMaterial.normalScale=new THREE.Vector2(.12,.12);
const cube=new THREE.BoxGeometry(1,1,1),sphere=new THREE.SphereGeometry(1,10,8),materials=new Map();
function mat(color){if(!materials.has(color))materials.set(color,new THREE.MeshStandardMaterial({color,roughness:.75}));return materials.get(color);}
function box(g,w,h,d,x,y,z,color){const m=new THREE.Mesh(cube,mat(color));m.scale.set(Math.max(w,.01),Math.max(h,.01),Math.max(d,.01));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;}
function person(o){const g=fitAsset('worker',o);const phase=[...(o.id||o.name||'worker')].reduce((n,c)=>n+c.charCodeAt(0),0)%31/30;animateWorker(g,'Idle',phase,1);return g;}
function distantRack(o){
 const parts=rackParts(o,true),mesh=new THREE.InstancedMesh(cube,mat('#ffffff'),parts.length),transform=new THREE.Object3D(),color=new THREE.Color();
 parts.forEach((p,i)=>{transform.position.set(p.x,p.y,p.z);transform.scale.set(p.w,p.h,p.d);transform.updateMatrix();mesh.setMatrixAt(i,transform.matrix);mesh.setColorAt(i,color.set(p.color));});
 mesh.instanceMatrix.needsUpdate=true;mesh.instanceColor.needsUpdate=true;mesh.computeBoundingSphere();return mesh;
}
function model(o){
 let g=new THREE.Group();const w=o.width,d=o.depth,h=o.height,c=o.color;
 if(['worker','forklift','pallet','box','conveyor','worktable','dock','handpallet','plastic-pallet'].includes(o.type))g=fitAsset(o.type,o);
 else if(['rack','boxrack','shelf'].includes(o.type)&&!rackPlan.compact){g=new THREE.LOD();g.userData.rackLOD=true;g.addLevel(rackAsset(o),0);g.addLevel(distantRack(o),$('qualityPreset').value==='low'?12:80,.15);}
 else if(['rack','boxrack','shelf'].includes(o.type)){
  const parts=rackParts(o,rackPlan.compact);
  const mesh=new THREE.InstancedMesh(cube,mat('#ffffff'),parts.length);
  const transform=new THREE.Object3D(),tint=new THREE.Color();
  parts.forEach((p,i)=>{
    transform.position.set(p.x,p.y,p.z);transform.scale.set(Math.max(p.w,.01),Math.max(p.h,.01),Math.max(p.d,.01));transform.updateMatrix();
    mesh.setMatrixAt(i,transform.matrix);mesh.setColorAt(i,tint.set(p.color));
  });
  mesh.instanceMatrix.needsUpdate=true;mesh.instanceColor.needsUpdate=true;
  mesh.computeBoundingBox();mesh.computeBoundingSphere();mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);
 }else if(o.type==='pallet'){for(let i=0;i<5;i++)box(g,w,h*.4,d/6,0,h*.8,-d/2+(i+.5)*d/5,c);for(const x of [-w*.35,0,w*.35])box(g,w*.1,h*.6,d,x,h*.3,0,'#9f7653');}
 else if(o.type==='conveyor'){box(g,w,.15,d,0,h-.05,0,'#425f70');for(let i=0;i<Math.min(35,Math.ceil(w/.3));i++)box(g,.07,.06,d*.9,-w/2+.15+i*.3,h+.05,0,'#b7c8cd');for(const x of [-w*.4,w*.4])for(const z of [-d*.35,d*.35])box(g,.1,h,.1,x,h/2,z,c);}
 else if(o.type==='worktable'){box(g,w,.12,d,0,h,0,c);for(const x of [-w*.42,w*.42])for(const z of [-d*.38,d*.38])box(g,.08,h,.08,x,h/2,z,'#526b79');}
 else if(o.type==='forklift'){box(g,w,h*.42,d*.6,0,h*.28,0,c);box(g,w*.82,h*.48,d*.32,0,h*.69,-d*.15,'#526874');box(g,.12,h,d*.06,-w*.42,h/2,d*.35,'#273f4c');box(g,.12,h,d*.06,w*.42,h/2,d*.35,'#273f4c');for(const x of [-w*.33,w*.33])box(g,.15,.1,d*.4,x,.1,d*.42,'#304a59');}
 else if(['office','cleanbooth','breakroom','lockerroom'].includes(o.type)){box(g,w,.08,d,0,.04,0,'#cbdbe1');box(g,w,h,.12,0,h/2,-d/2,c);for(const x of [-w/2,w/2])box(g,.12,h,d,x,h/2,0,c);box(g,w,h*.1,d,0,h,0,'#a8c9d4');}
 else if(o.type==='dock'||o.type==='door'){for(const x of [-w/2,w/2])box(g,.12,h,d,x,h/2,0,c);box(g,w,.16,d,0,h,0,c);if(o.type==='dock')box(g,w,h*.4,.1,0,h*.8,-d/2,'#b4c7cf');}
 else if(o.type==='waypoint'){box(g,w,.035,d,0,.02,0,c);box(g,.055,1.7,.055,0,.85,0,'#588c85');box(g,.6,.32,.025,.27,1.5,0,c);}
 else box(g,w,h,d,0,h/2,0,c);
 const p=toWorld(o);g.position.set(p.x,p.y,p.z);g.rotation.y=rotationRadians(o.rotation);g.userData.id=o.id;return g;
}
function clearPaths(){for(const c of [...pathRoot.children]){c.geometry?.dispose();c.material?.dispose();pathRoot.remove(c);}}
function rebuild(){
 rackPlan=rackRenderPlan(layout.objects);
 releaseInstance(objectsRoot);releaseInstance(agentRoot);
 buildShell();
 objectsRoot.clear();groups.clear();agentRoot.clear();simGroups.clear();clearPaths();groundRoot.traverse(m=>{if(m.userData.background){m.geometry.dispose();m.material.map.dispose();m.material.dispose();}});groundRoot.clear();if(grid){grid.geometry.dispose();grid.material.dispose();grid=null;}
 const w=layout.warehouse;const floor=box(groundRoot,w.width,.18,w.depth,w.width/2,-.12,w.depth/2,'#b9bfc0');floor.material=floorMaterial;if(layout.background){const b=layout.background,t=textureLoader.load(b.data);t.colorSpace=THREE.SRGBColorSpace;const image=new THREE.Mesh(new THREE.PlaneGeometry(b.width,b.depth),new THREE.MeshBasicMaterial({map:t,transparent:true,opacity:b.opacity,depthWrite:false}));image.rotation.x=-Math.PI/2;image.position.set(b.x,.001,b.y);image.userData.background=true;groundRoot.add(image);}for(const z of [0,w.depth])box(groundRoot,w.width,.14,.09,w.width/2,.02,z,'#77969e');for(const x of [0,w.width])box(groundRoot,.09,.14,w.depth,x,.02,w.depth/2,'#77969e');
 grid=new THREE.GridHelper(Math.max(w.width,w.depth),Math.round(Math.max(w.width,w.depth)),0x97b2b9,0xc8d6d9);grid.position.set(w.width/2,.005,w.depth/2);grid.visible=topView;groundRoot.add(grid);
 for(const o of layout.objects){const g=model(o);groups.set(o.id,g);objectsRoot.add(g);}sim=null;cargoGroups.clear();playing=false;reviewCount=layout.objects.filter(o=>placementError(o,layout)).length;select(selected);syncFields();if(rackPlan.compact)$('review').textContent+='\n대용량 도면: 랙 내부 표시만 간소화합니다. 실제 베이·단수·용량·저장 데이터는 유지됩니다.';minimap();stats();
}
function iso(){camera=perspective;controls.object=camera;topView=false;if(grid)grid.visible=false;const w=layout.warehouse,s=Math.max(w.width,w.depth);controls.target.set(w.width/2,0,w.depth/2);camera.position.set(w.width/2+s*.76,s*.9,w.depth/2+s*.9);camera.lookAt(controls.target);controls.update();}
function top(){camera=orthographic;controls.object=camera;const rect=$('stage').getBoundingClientRect(),span=Math.max(layout.warehouse.depth,layout.warehouse.width/(rect.width/rect.height))*1.12;camera.left=-span*rect.width/rect.height/2;camera.right=-camera.left;camera.top=span/2;camera.bottom=-span/2;camera.updateProjectionMatrix();topView=true;if(grid)grid.visible=true;const w=layout.warehouse;controls.target.set(w.width/2,0,w.depth/2);camera.position.set(w.width/2,Math.max(w.width,w.depth)*1.45,w.depth/2+.01);camera.lookAt(controls.target);controls.update();}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,4500);}
function flushSave(){clearTimeout(dirtyTimer);if(autosaveBlocked){$('saveState').textContent='원본 보호: 자동 저장 중지 · JSON으로 내보내세요';return;}try{localStorage.setItem(KEY,JSON.stringify(layout));$('saveState').textContent='이 브라우저에 자동 저장됨 · GitHub 커밋은 별도';}catch{$('saveState').textContent='브라우저 저장 실패 — JSON으로 내보내세요';toast('브라우저 저장 공간 / 권한을 확인하세요.');}}
function persist(){clearTimeout(dirtyTimer);dirtyTimer=setTimeout(flushSave,250);}
window.addEventListener('pagehide',()=>{if(dirtyTimer)flushSave();});
function commit(){layout=normalize(layout);history.push(layout);persist();rebuild();}
function replace(next){if(mode!=='edit')setMode('edit');layout=normalize(next);selected=null;tool=null;removeGhost();history.push(layout);persist();rebuild();iso();}
function syncFields(){ $('projectName').value=layout.projectName;const w=layout.warehouse;$('workerSpeed').value=layout.simulation.speed;$('workerDwell').value=layout.simulation.dwell;$('warehouseW').value=w.width;$('warehouseD').value=w.depth;$('warehouseH').value=w.height;$('review').textContent=reviewCount?`경계 / 겹침 검토 필요: ${reviewCount}개 설비.\n실제 설비 배치·피난·통로 폭은 별도 안전 검토가 필요합니다.`:'설계 → 운영 → 내부 체험 순서로 확인하세요.\n브라우저 자동 저장과 GitHub 저장은 별개입니다.';const legacy=layout.objects.filter(o=>!Object.hasOwn(CATALOG,o.type));if(legacy.length)$('review').textContent+=`\n구버전 특수 설비 ${legacy.length}개: 원본 속성을 보존하며 단순 외형으로 표시합니다. 상세 편집은 기존 편집기를 사용하세요.`;}
function select(id){selected=layout.objects.some(o=>o.id===id)?id:null;if(selectionBox){scene.remove(selectionBox);selectionBox.geometry.dispose();selectionBox.material.dispose();selectionBox=null;}const o=layout.objects.find(o=>o.id===selected);$('selectionEmpty').hidden=!!o;$('inspector').hidden=!o;if(!o)return;
 for(const [f,k] of Object.entries({objectName:'name',ox:'x',oy:'y',ow:'width',od:'depth',oh:'height',oz:'z',or:'rotation'}))$(f).value=o[k];$('ol').checked=o.locked;$('objectColor').value=o.color;$('rackConfig').hidden=!['rack','boxrack','shelf'].includes(o.type);$('rackBays').value=o.config?.bays||4;$('rackLevels').value=o.config?.levels||4;$('oneWay').value=o.config?.oneWay||'';$('allowedResource').value=o.config?.allowed?.join(',')||'';
 const g=groups.get(o.id);if(g&&mode==='edit'){selectionBox=new THREE.BoxHelper(g,0x1ab698);scene.add(selectionBox);}}
function catalogue(){const q=$('search').value.toLowerCase(),cat=$('category').value;$('catalog').replaceChildren();for(const [type,d]of Object.entries(CATALOG)){if((cat!=='전체'&&cat!==d.group)||!d.name.toLowerCase().includes(q))continue;const b=document.createElement('button');b.className='asset'+(tool===type?' active':'');b.title=`${d.width} × ${d.depth} × ${d.height}m`;const image=thumbnail(type,d),icon=document.createElement(image?'img':'span');if(image){icon.src=image;icon.alt=d.name+' 3D 미리보기';}else icon.textContent=d.icon;const text=document.createElement('b');text.textContent=d.name;const size=document.createElement('small');size.textContent=`${d.width} × ${d.depth}m`;b.append(icon,text,size);b.onclick=()=>{tool=tool===type?null:type;rotation=0;brush=null;select(null);removeGhost();catalogue();$('bottomhint').textContent=tool?`${d.name} · 바닥 클릭으로 배치 · R 회전 · Esc 취소`:'설비를 고르고 바닥을 클릭하세요';if(innerWidth<850)$('left').classList.remove('open');};$('catalog').append(b);}}
function removeGhost(){if(ghost){releaseInstance(ghost);scene.remove(ghost);ghost.traverse(m=>{if(m.isInstancedMesh)m.dispose();if(m.material)m.material.dispose();});ghost=null;}}
function setGhost(p){if(!tool)return;const o=object(tool,Math.round(p.x*2)/2,Math.round(p.z*2)/2,{...(brush?copy(brush):{}),id:uid(),x:Math.round(p.x*2)/2,y:Math.round(p.z*2)/2,rotation,locked:false});if(!ghost){ghost=model(o);ghost.traverse(m=>{if(m.material){m.material=m.material.clone();m.material.transparent=true;m.material.opacity=.48;if(m.isInstancedMesh){for(let i=0;i<m.count;i++)m.setColorAt(i,new THREE.Color('#ffffff'));m.instanceColor.needsUpdate=true;}}});scene.add(ghost);}ghost.position.set(o.x,0,o.y);ghost.rotation.y=rotation*Math.PI/180;const invalid=placementError(o,layout);ghost.traverse(m=>{if(m.material)m.material.color.set(invalid?'#d35c4b':'#44b89e');});return o;}
const ray=new THREE.Raycaster(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
function point(e){const r=$('scene').getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);return ray.ray.intersectPlane(plane,new THREE.Vector3());}
function hit(){let fallback=null;for(const h of ray.intersectObjects(objectsRoot.children,true)){let g=h.object;while(g.parent&&g.parent!==objectsRoot)g=g.parent;const o=layout.objects.find(o=>o.id===g.userData.id);if(o&&o.type!=='aisle'&&o.type!=='safety')return o;if(o)fallback=o;}return fallback;}
const canvas=$('scene');canvas.addEventListener('pointerdown',e=>{
 canvas.focus();if(mode==='walk'){pointerDown={x:e.clientX,y:e.clientY,touch:e.pointerType==='touch'};canvas.setPointerCapture(e.pointerId);return;}if(mode!=='edit'||e.button!==0)return;
 const p=point(e);if(!p)return;pointerDown={x:e.clientX,y:e.clientY};if(tool){controls.enabled=false;return;}const o=hit();if(e.shiftKey&&o){if(multiSelected.has(o.id))multiSelected.delete(o.id);else multiSelected.add(o.id);$('multiCount').textContent=multiSelected.size+'개 선택';select(o.id);controls.enabled=true;pointerDown=null;return;}select(o?.id);if(o&&!o.locked){controls.enabled=false;drag={id:o.id,start:copy(o),offset:{x:o.x-p.x,y:o.y-p.z}};canvas.setPointerCapture(e.pointerId);}
});
canvas.addEventListener('pointermove',e=>{
 if(mode==='walk'){if(document.pointerLockElement===canvas){yaw-=e.movementX*.0025;pitch=clamp(pitch-e.movementY*.0025,-1.4,1.4);}else if(pointerDown){yaw-=(e.clientX-pointerDown.x)*.004;pitch=clamp(pitch-(e.clientY-pointerDown.y)*.004,-1.4,1.4);pointerDown.x=e.clientX;pointerDown.y=e.clientY;}return;}
 if(mode!=='edit')return;const p=point(e);if(!p)return;if(tool)setGhost(p);if(drag){const o=layout.objects.find(o=>o.id===drag.id);o.x=Math.round((p.x+drag.offset.x)*2)/2;o.y=Math.round((p.z+drag.offset.y)*2)/2;groups.get(o.id).position.set(o.x,o.z,o.y);selectionBox?.update();}
});
canvas.addEventListener('pointerup',e=>{
 if(mode==='edit'){if(tool&&pointerDown&&Math.hypot(e.clientX-pointerDown.x,e.clientY-pointerDown.y)<8){const p=point(e);if(p){const o=setGhost(p),err=placementError(o,layout);if(err)toast(err);else if(layout.objects.length>=MAX_OBJECTS)toast('최대 설비 수에 도달했습니다.');else{layout.objects.push(o);selected=o.id;commit();}}}
 if(drag){const o=layout.objects.find(o=>o.id===drag.id),err=placementError(o,layout);if(err){Object.assign(o,drag.start);toast(err);rebuild();}else if(o.x!==drag.start.x||o.y!==drag.start.y)commit();}}
 drag=null;pointerDown=null;controls.enabled=mode!=='walk';if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);
});
canvas.addEventListener('pointercancel',()=>{if(drag){Object.assign(layout.objects.find(o=>o.id===drag.id),drag.start);rebuild();}drag=null;pointerDown=null;controls.enabled=mode!=='walk';});
canvas.addEventListener('contextmenu',e=>e.preventDefault());
function cancelTool(){tool=null;brush=null;removeGhost();catalogue();$('bottomhint').textContent='설비 선택 → 바닥 클릭 · 우클릭 회전 · 휠 확대';}
function modify(fn){if(mode!=='edit')return;const o=layout.objects.find(o=>o.id===selected);if(!o)return;if(o.locked){toast('잠긴 설비입니다. 잠금을 먼저 해제하세요.');return;}const next=copy(o);fn(next);const err=placementError(next,layout);if(err){toast(err);return;}Object.assign(o,next);commit();}
function deleteSelected(){if(mode!=='edit')return;const o=layout.objects.find(o=>o.id===selected);if(!o)return;if(o.locked){toast('잠긴 설비입니다.');return;}layout.objects=layout.objects.filter(x=>x.id!==selected);selected=null;commit();}
$('rotateBtn').onclick=()=>modify(o=>o.rotation=(o.rotation+90)%360);$('deleteBtn').onclick=deleteSelected;
$('duplicateBtn').onclick=()=>{if(mode!=='edit')return;const o=layout.objects.find(o=>o.id===selected);if(!o)return;tool=o.type;brush=copy(o);rotation=o.rotation;removeGhost();catalogue();toast('선택한 설비의 크기와 설정을 복제합니다. 바닥을 클릭하세요.');};
$('applyObject').onclick=()=>{const o=layout.objects.find(o=>o.id===selected);if(!o||mode!=='edit')return;const next=copy(o);if(o.locked&&$('ol').checked){toast('위치 잠금을 해제한 뒤 변경하세요.');return;}next.name=$('objectName').value.trim()||o.name;for(const [f,k]of Object.entries({ox:'x',oy:'y',ow:'width',od:'depth',oh:'height',oz:'z',or:'rotation'})){const value=Number($(f).value);if(!Number.isFinite(value)||$(f).value===''){toast('숫자 입력을 확인하세요.');return;}next[k]=value;}if(next.width<.05||next.depth<.05||next.height<.01||next.z<0){toast('크기 / 높이는 양수여야 합니다.');return;}next.config={...next.config};if(o.type==='aisle')next.config.oneWay=$('oneWay').value;if(o.type==='safety')next.config.allowed=$('allowedResource').value?$('allowedResource').value.split(','):[];next.locked=$('ol').checked;next.color=$('objectColor').value;if(!$('rackConfig').hidden){const bays=Number($('rackBays').value),levels=Number($('rackLevels').value);if(![bays,levels].every(v=>Number.isInteger(v)&&v>=1&&v<=20)){toast('랙 칸 수와 단 수는 1~20의 정수로 입력하세요.');return;}next.config={...next.config,bays,levels};}const err=placementError(next,layout);if(err){toast(err);return;}Object.assign(o,next);commit();};
$('resizeBtn').onclick=()=>{if(mode!=='edit')return;const w={width:Number($('warehouseW').value),depth:Number($('warehouseD').value),height:Number($('warehouseH').value)};if(!Object.values(w).every(Number.isFinite)||w.width<10||w.width>200||w.depth<10||w.depth>200||w.height<3||w.height>30){toast('가로·세로 10~200m, 높이 3~30m로 입력하세요.');return;}const next={...layout,warehouse:w};if(layout.objects.some(o=>footprint(o).some(p=>p.x<0||p.y<0||p.x>w.width||p.y>w.depth)||o.z+o.height>w.height)){toast('배치된 설비가 새 창고 경계를 벗어납니다.');return;}layout.warehouse=w;commit();iso();};
$('projectName').onchange=()=>{layout.projectName=$('projectName').value.trim()||'나의 물류센터';commit();};
function undo(){if(mode!=='edit')return;cancelTool();layout=history.undo();persist();rebuild();}function redo(){if(mode!=='edit')return;cancelTool();layout=history.redo();persist();rebuild();}
$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('isoBtn').onclick=()=>{if(mode!=='walk')iso();};$('topBtn').onclick=()=>{if(mode!=='walk')top();};
$('search').oninput=catalogue;$('category').onchange=catalogue;
$('demoBtn').onclick=()=>{if(confirm('현재 도면을 템플릿으로 바꿀까요? 실행 취소로 복구할 수 있습니다.'))replace(demo());};
$('blankBtn').onclick=()=>{if(confirm('빈 창고를 만들까요? 실행 취소로 복구할 수 있습니다.'))replace({...demo(),projectName:'새 물류센터',objects:[]});};
let rowPreview=null;
function readRackPlan(){return planRacks(layout,{x:Number($('rowX').value),y:Number($('rowY').value),columns:Number($('rowCount').value),gap:Number($('rowGap').value),rows:Number($('rackRows').value),width:Number($('rowWidth').value),depth:Number($('rowDepth').value),height:Number($('rowHeight').value),bays:Number($('rowBays').value),levels:Number($('rowLevels').value),aisle:Number($('rowAisle').value),wall:Number($('rowWall').value),doubleSided:$('rowDouble').checked});}
$('rowBtn').onclick=()=>{$('rowDialog').showModal();rowPreview=null;};$('rowClose').onclick=()=>$('rowDialog').close();
$('rowPreview').onclick=()=>{try{rowPreview=readRackPlan();$('rowSummary').textContent=`설비 ${rowPreview.added.length}개 · 팔레트 ${rowPreview.capacity.palletPositions}위치`+(rowPreview.errors.length?'\n'+rowPreview.errors.map(e=>`(${e.x}, ${e.y}) ${e.error}`).join('\n'):' · 배치 가능');const c=$('rowMap'),ctx=c.getContext('2d'),scale=Math.min(c.width/layout.warehouse.width,c.height/layout.warehouse.depth);ctx.clearRect(0,0,c.width,c.height);for(const o of [...layout.objects,...rowPreview.added]){ctx.fillStyle=rowPreview.errors.some(e=>e.id===o.id)?'#da493d':rowPreview.added.includes(o)?'#1a9c80':'#a5b3be';ctx.fillRect((o.x-o.width/2)*scale,(o.y-o.depth/2)*scale,o.width*scale,o.depth*scale);}}catch(e){toast(e.message);}};
$('rowApply').onclick=()=>{try{const plan=readRackPlan();if(plan.errors.length){toast(plan.errors[0].error+' · 전체 배치를 취소했습니다.');return;}replace(plan.next);$('rowDialog').close();}catch(e){toast(e.message);}};
function exportJSON(){const blob=new Blob([JSON.stringify(layout,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=layout.projectName.replace(/[\\/:*?"<>|]/g,'_')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('exportBtn').onclick=exportJSON;$('backupBtn').onclick=exportJSON;$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>5_000_000)throw Error('5MB 이하 JSON만 불러올 수 있습니다.');const next=normalize(JSON.parse(await f.text()));if(confirm('현재 도면을 불러온 도면으로 바꿀까요?'))replace(next);}catch(err){toast(err.message);}finally{e.target.value='';}};
$('legacyImport').onclick=()=>{try{const old=localStorage.getItem(OLD);if(!old)throw Error('이 브라우저에 기존 도면이 없습니다. 기존 편집기에서 JSON을 내보내 불러오세요.');const raw=JSON.parse(old),next=normalize(raw.project||raw);if(confirm('기존 도면을 새 편집기로 가져올까요? 기존 저장 데이터는 변경하지 않습니다.'))replace(next);}catch(e){toast(e.message);}};
function spawn(){const workers=layout.objects.filter(o=>o.type==='worker');let p=workers.find(o=>!blocked(o.x,o.y,layout));if(!p)for(let y=layout.warehouse.depth-.5;y>.3&&!p;y-=.75)for(let x=.5;x<layout.warehouse.width-.3;x+=.75)if(!blocked(x,y,layout)){p={x,y};break;}if(!p){toast('걸어갈 수 있는 공간이 없습니다.');return false;}const candidates=[{x:p.x,y:p.y+.9},{x:p.x+.9,y:p.y},{x:p.x,y:p.y-.9}];const safe=candidates.find(q=>!blocked(q.x,q.y,layout))||p;const aisle={x:layout.warehouse.width/2,y:layout.warehouse.depth-2};walk=!blocked(aisle.x,aisle.y,layout)?aisle:{x:safe.x,y:safe.y};yaw=0;pitch=0;return true;}
function setupSimulation(){if(sim)return;simAccumulator=0;sim=operationKind==='tasks'?new Logistics(layout):new Simulation(layout);if(sim.error)toast(sim.error);for(const o of layout.objects)if(o.type==='worker'||operationKind==='tasks'&&o.type==='forklift')groups.get(o.id).visible=false;for(const a of sim.agents){const g=a.type==='forklift'?fitAsset('forklift',a):person(a);g.position.set(a.x,0,a.y);agentRoot.add(g);simGroups.set(a.id,g);}if(operationKind==='tasks')for(const g of groups.values())g.traverse(m=>{if(['pallet','box'].includes(m.userData.assetPart))m.visible=false;});drawPaths();}
function drawPaths(){clearPaths();if(!sim||!$('paths').checked)return;for(const a of sim.agents){if(a.path.length<2)continue;const geom=new THREE.BufferGeometry().setFromPoints(a.path.map(p=>new THREE.Vector3(p.x,.08,p.y)));pathRoot.add(new THREE.Line(geom,new THREE.LineBasicMaterial({color:0x218b83,transparent:true,opacity:.7})));}}
function setMode(next){
 if(next===mode)return;if(drag){Object.assign(layout.objects.find(o=>o.id===drag.id),drag.start);drag=null;rebuild();}cancelTool();pointerDown=null;keys.clear();if(document.pointerLockElement)document.exitPointerLock();if(mode==='walk'&&savedView){camera.position.copy(savedView.p);controls.target.copy(savedView.t);camera.lookAt(controls.target);controls.update();}const keepPlaying=playing;mode=next;playing=mode!=='edit'&&keepPlaying;document.body.className=mode;$('left').classList.remove('open');$('right').classList.remove('open');$('runBtn').hidden=mode==='edit';shellRoot.visible=mode==='walk';labelRoot.visible=mode!=='walk';
 document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('simTools').hidden=mode!=='sim';$('walkTools').hidden=mode!=='walk';$('editSettings').hidden=mode!=='edit';$('projectName').disabled=mode!=='edit';$('undoBtn').disabled=mode!=='edit';$('redoBtn').disabled=mode!=='edit';$('topBtn').disabled=mode==='walk';$('isoBtn').disabled=mode==='walk';controls.enabled=mode!=='walk';agentRoot.visible=mode!=='edit';pathRoot.visible=mode==='sim';
 for(const o of layout.objects)if(o.type==='worker'||operationKind==='tasks'&&o.type==='forklift')groups.get(o.id).visible=mode==='edit';
 for(const o of layout.objects)if(o.type==='waypoint')groups.get(o.id).visible=mode!=='walk';
 $('modeLabel').textContent={edit:'BUILD YOUR WAREHOUSE',sim:'SIMULATE YOUR WORKFLOW',walk:'STEP INSIDE YOUR DESIGN'}[mode];$('modeTitle').textContent={edit:'생각한 대로, 바로 배치',sim:'작업자의 동선을 확인',walk:'내가 만든 창고 속으로'}[mode];$('modeDesc').textContent={edit:'설비를 고르고 바닥을 클릭하세요. R 회전 · Esc 취소',sim:'설비를 피하며 목적지를 순서대로 방문합니다.',walk:'작업자 눈높이에서 공간과 통로를 살펴보세요.'}[mode];$('sceneMode').textContent={edit:'설계 모드',sim:'운영 시뮬레이션',walk:'1인칭 내부 체험'}[mode];$('sceneDetail').textContent=mode==='sim'?'· 동선 검토용 단순 모델':mode==='walk'?'· 눈높이 이동':'· 클릭으로 배치';$('bottomhint').textContent=mode==='walk'?'WASD 이동 · 화면 드래그 / 마우스 둘러보기 · Esc 잠금 해제':mode==='sim'?'시작 버튼을 눌러 작업자 동선을 확인하세요':'설비 선택 → 바닥 클릭 · 우클릭 회전 · 휠 확대';
 if(mode!=='edit')setupSimulation();syncPlayLabels();
 if(mode==='walk'){if(camera.isOrthographicCamera)iso();savedView={p:camera.position.clone(),t:controls.target.clone()};if(!spawn()){setMode('edit');return;}}
 for(const g of groups.values())g.traverse(m=>{if(['pallet','box'].includes(m.userData.assetPart))m.visible=mode==='edit'||operationKind!=='tasks';});select(selected);stats();minimap();
}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode===mode?mode:b.dataset.mode));
function syncPlayLabels(){$('playBtn').textContent=playing?'일시 정지':'시뮬레이션 시작';$('runBtn').textContent=playing?'Ⅱ 정지':'▶ 재생';}
function togglePlay(){setupSimulation();if(sim.error){toast(sim.error);return;}if(!sim.agents.length||!sim.targets.length){toast('설계 모드에서 작업자와 이동 목적지를 먼저 배치하세요.');return;}playing=!playing;syncPlayLabels();}
$('playBtn').onclick=togglePlay;$('runBtn').onclick=togglePlay;
$('resetSim').onclick=()=>{rebuild();setupSimulation();syncPlayLabels();};$('paths').onchange=drawPaths;
$('lockBtn').onclick=async()=>{try{if(mode==='walk'&&canvas.requestPointerLock)await canvas.requestPointerLock();else toast('화면을 드래그해서 둘러보세요.');}catch{toast('마우스 잠금을 사용할 수 없습니다. 화면 드래그로 둘러보세요.');}};$('spawnBtn').onclick=spawn;
window.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(mode==='walk'&&['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight'].includes(e.code)){keys.add(e.code);e.preventDefault();return;}if(e.key==='Escape'){cancelTool();select(null);}if(mode!=='edit')return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();}if(e.code==='KeyR'){if(tool){rotation=(rotation+90)%360;removeGhost();}else modify(o=>o.rotation=(o.rotation+90)%360);}if(e.key==='Delete')deleteSelected();});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();pointerDown=null;});document.addEventListener('visibilitychange',()=>{keys.clear();lastTime=performance.now();});
document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{keys.add(b.dataset.key);b.setPointerCapture(e.pointerId);e.preventDefault();};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.key);});
function walkTick(dt){const eye=clamp(Number($('eyeHeight').value)||1.65,1.2,1.9),speed=keys.has('ShiftLeft')||keys.has('ShiftRight')?3:1.5;const f=Number(keys.has('KeyW')||keys.has('ArrowUp'))-Number(keys.has('KeyS')||keys.has('ArrowDown')),r=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft'));const norm=Math.hypot(f,r)||1;const dx=(-Math.sin(yaw)*f+Math.cos(yaw)*r)/norm*speed*dt,dy=(-Math.cos(yaw)*f-Math.sin(yaw)*r)/norm*speed*dt;if(!blocked(walk.x+dx,walk.y,layout))walk.x+=dx;if(!blocked(walk.x,walk.y+dy,layout))walk.y+=dy;camera.position.set(walk.x,eye,walk.y);camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0);}
function stats(){let values;if(mode!=='edit'&&sim){values=[['모의 경과 시간',sim.time.toFixed(1),'초'],['이동 거리',sim.distance.toFixed(1),'m'],['목적지 도착',sim.arrivals,'회'],['경로 오류',sim.agents.filter(a=>['경로 없음','시작 위치 막힘','목적지 없음'].includes(a.status)).length,'명']];if(sim instanceof Logistics){const m=sim.metrics();values=[['모의 경과 시간',m.time.toFixed(1),'초'],['출하 완료',m.shipped,'단위'],['자원 대기',m.waiting.toFixed(1),'초'],['수량 보존',m.conservation.valid?'정상':'오류','']];}$('agentList').replaceChildren();for(const a of sim.agents){const row=document.createElement('div');row.textContent=`${a.name} · ${a.status} · ${a.distance.toFixed(1)}m`;$('agentList').append(row);}}else{const totalCapacity=capacity(layout.objects).palletPositions;values=[['바닥 면적',layout.warehouse.width*layout.warehouse.depth,'㎡'],['배치 설비',layout.objects.length,'개'],['팔레트 랙 용량',totalCapacity,'위치'],['배치 검토',reviewCount,'건']];}values.forEach(([l,v,u],i)=>{$(`s${i+1}l`).textContent=l;$(`s${i+1}`).textContent=v;$(`s${i+1}u`).textContent=u;});}
function minimap(){const c=$('minimap'),ctx=c.getContext('2d'),w=layout.warehouse,s=Math.min((c.width-24)/w.width,(c.height-24)/w.depth);ctx.clearRect(0,0,c.width,c.height);ctx.save();ctx.translate((c.width-w.width*s)/2,(c.height-w.depth*s)/2);ctx.scale(s,s);ctx.fillStyle='#e5eef1';ctx.fillRect(0,0,w.width,w.depth);for(const o of layout.objects){if(o.type==='worker'&&mode!=='edit')continue;const poly=footprint(o);ctx.beginPath();poly.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=o.color;ctx.fill();}if(mode!=='edit'&&sim)for(const a of sim.agents){ctx.fillStyle='#e35e44';ctx.beginPath();ctx.arc(a.x,a.y,.45,0,Math.PI*2);ctx.fill();}if(mode==='walk'){ctx.translate(walk.x,walk.y);ctx.rotate(-yaw);ctx.fillStyle='#dd563b';ctx.beginPath();ctx.moveTo(0,-.9);ctx.lineTo(-.5,.5);ctx.lineTo(.5,.5);ctx.closePath();ctx.fill();}ctx.restore();}
const resize=new ResizeObserver(()=>{const r=$('stage').getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();});resize.observe($('stage'));
function animate(now){const dt=Math.min((now-lastTime)/1000,.06);lastTime=now;if(mode==='walk'){if(document.querySelector('dialog[open]'))keys.clear();walkTick(dt);}else controls.update();if(mode!=='edit'&&sim){if(playing&&!document.hidden){simAccumulator+=dt*Number($('simSpeed').value);while(simAccumulator>=STEP){sim.tick(STEP);simAccumulator-=STEP;}}for(const a of sim.agents){const g=simGroups.get(a.id);g.position.set(a.x,0,a.y);g.rotation.y=a.heading;animateWorker(g,a.cargo?'Carry':['이동','복귀','재탐색'].includes(a.status)?'Walk':['작업 중','적재','하역 / 포장'].includes(a.status)?'PickPlace':'Idle',playing?dt*Number($('simSpeed').value):0,layout.simulation.speed);if(a.type==='forklift'){g.traverse(m=>{if(m.name.startsWith('Wheel')){m.userData.baseRotation??=m.quaternion.clone();m.quaternion.copy(m.userData.baseRotation).multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),a.distance/.25));}});const fork=g.getObjectByName('ForkCarriage');if(fork)fork.position.y=.12+(a.phase==='unload'?.35:.1);}}}
 if(sim?.units){for(const u of sim.units){let cargo=cargoGroups.get(u.id);if(!cargo){cargo=fitAsset('box',{width:.6,height:.4,depth:.4});const pallet=fitAsset('pallet',{width:1.2,height:.16,depth:1});pallet.position.y=-.16;cargo.add(pallet);cargo.userData.loadPallet=pallet;cargoGroups.set(u.id,cargo);agentRoot.add(cargo);}const owner=sim.agents.find(a=>a.id===u.owner&&a.cargo===u.id);cargo.visible=u.state!=='shipped'&&(u.state!=='inbound'||u.id===sim.units.find(v=>v.state==='inbound')?.id&&sim.agents.every(a=>a.type!=='forklift'||Math.hypot(a.x-u.point.x,a.y-u.point.y)>2.5));cargo.userData.loadPallet.visible=owner?owner.type==='forklift':['inbound','stored'].includes(u.state);if(owner){const g=simGroups.get(owner.id);if(cargo.parent!==g)g.add(cargo);cargo.position.set(0,owner.type==='forklift'?.38:1.05,owner.type==='forklift'?1.2:.37);}else{if(cargo.parent!==agentRoot)agentRoot.add(cargo);const slot=u.state==='stored'?sim.slots.find(s=>s.id===u.slot)?.visual:null;if(slot)cargo.position.set(slot.x,slot.z,slot.y);else cargo.position.set(u.point.x,.2,u.point.y);}}}
 if(now-uiTimer>220){if(rackPlan.compact){const nearest=layout.objects.filter(o=>['rack','boxrack','shelf'].includes(o.type)).map(o=>({o,d:Math.hypot(o.x-camera.position.x,o.y-camera.position.z)})).filter(v=>v.d<20).sort((a,b)=>a.d-b.d).slice(0,6);const ids=new Set(nearest.map(v=>v.o.id));for(const o of layout.objects){const g=groups.get(o.id);if(!g||!['rack','boxrack','shelf'].includes(o.type))continue;if(ids.has(o.id)&&!g.userData.detail){const detail=rackAsset(o);g.children.forEach(m=>m.visible=false);g.add(detail);g.userData.detail=detail;}else if(!ids.has(o.id)&&g.userData.detail){releaseInstance(g.userData.detail);g.remove(g.userData.detail);g.userData.detail=null;g.children.forEach(m=>m.visible=true);}}}stats();minimap();if(mode!=='edit'&&sim){const signature=sim.agents.map(a=>a.target).join(',');if(signature!==pathRoot.userData.signature){drawPaths();pathRoot.userData.signature=signature;}}uiTimer=now;}renderer.render(scene,camera);requestAnimationFrame(animate);}
// Tokens live only in the open password field / request closure; never in storage, URLs or exported layouts.
let ghBusy=false;const known=new Map();
function ghSettings(){const owner=$('ghOwner').value.trim(),repo=$('ghRepo').value.trim(),path=$('ghPath').value.trim(),branch=$('ghBranch').value.trim();const url=repoPath(owner,repo,path);if(!branch||branch.length>200)throw Error('브랜치를 입력하세요.');return {owner,repo,path,branch,url,key:`${owner}/${repo}/${branch}/${path}`};}
async function api(url,options={}){return githubRequest(url,{...options,token:$('ghToken').value.trim()});}
async function ghRun(fn){if(ghBusy)return;ghBusy=true;['ghSave','ghLoad','ghList','ghClose','ghOwner','ghRepo','ghBranch','ghPath','ghToken','ghFiles','ghConsent'].forEach(id=>$(id).disabled=true);$('ghStatus').textContent='GitHub 요청 중…';try{await fn();}catch(e){$('ghStatus').textContent=e.message;}finally{ghBusy=false;['ghSave','ghLoad','ghList','ghClose','ghOwner','ghRepo','ghBranch','ghPath','ghToken','ghFiles','ghConsent'].forEach(id=>$(id).disabled=false);}}
$('githubBtn').onclick=()=>{keys.clear();if(document.pointerLockElement)document.exitPointerLock();$('githubDialog').showModal();};$('ghClose').onclick=()=>{$('ghToken').value='';$('ghConsent').checked=false;$('githubDialog').close();};$('githubDialog').addEventListener('cancel',e=>{if(ghBusy)e.preventDefault();});$('githubDialog').addEventListener('close',()=>{$('ghToken').value='';$('ghConsent').checked=false;});
$('ghSave').onclick=()=>ghRun(async()=>{if(!$('ghToken').value.trim())throw Error('저장하려면 이 저장소의 Contents 쓰기 권한 토큰이 필요합니다.');if(!$('ghConsent').checked)throw Error('도면 공개 범위를 확인하고 확인란을 선택하세요.');const s=ghSettings(),current=await api(s.url+'?ref='+encodeURIComponent(s.branch),{allow404:true});if(current&&current.type!=='file')throw Error('파일 경로를 확인하세요.');const expected=known.get(s.key);if(expected&&current?.sha!==expected)throw Error('다른 사용자가 이 도면을 변경했습니다. 최신 도면을 다시 열고 병합하세요.');if(current&&!expected&&!confirm('동일 이름의 GitHub 도면이 있습니다. 현재 도면으로 덮어쓸까요? 이전 버전은 GitHub 커밋 기록에 남습니다.')){ $('ghStatus').textContent='저장을 취소했습니다.';return;}
 const serialized=JSON.stringify(layout,null,2);if(new TextEncoder().encode(serialized).length>950000)throw Error('GitHub 직접 저장은 도면 950KB까지 지원합니다. JSON으로 내보내 보관하세요.');const body={message:`layout: ${layout.projectName}`,branch:s.branch,content:utf8base64(serialized)};if(current)body.sha=current.sha;const result=await api(s.url,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});known.set(s.key,result.content.sha);$('ghStatus').textContent=`커밋 완료: ${result.commit.sha.slice(0,7)} · ${s.path}`;$('saveState').textContent=`GitHub 저장 완료 · ${result.commit.sha.slice(0,7)}`;try{localStorage.setItem('warehouse-city-github',JSON.stringify({owner:s.owner,repo:s.repo,branch:s.branch,path:s.path}));}catch{}toast('GitHub 도면 저장 완료');});
$('ghList').onclick=()=>ghRun(async()=>{const s=ghSettings(),base=`https://api.github.com/repos/${encodeURIComponent(s.owner)}/${encodeURIComponent(s.repo)}/contents/layouts?ref=${encodeURIComponent(s.branch)}`,items=await api(base,{allow404:true});$('ghFiles').replaceChildren();const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent='도면을 선택하세요';$('ghFiles').append(placeholder);for(const f of Array.isArray(items)?items:[]){if(f.type==='file'&&f.name.endsWith('.json')&&f.name!=='index.json'){const opt=document.createElement('option');opt.value=f.path;opt.textContent=f.name;$('ghFiles').append(opt);}}$('ghStatus').textContent=`도면 ${$('ghFiles').options.length-1}개. 목록은 layouts 바로 아래 파일을 표시합니다.`;});
$('ghBackup').onclick=exportJSON;
$('ghCompare').onclick=()=>ghRun(async()=>{const settings=ghSettings(),file=await api(settings.url+'?ref='+encodeURIComponent(settings.branch));const remote=normalize(JSON.parse(fromBase64(file.content))),diff=compareLayouts(layout,remote);$('ghStatus').textContent=`최신 SHA ${file.sha.slice(0,7)} · 로컬에만 ${diff.localOnly.length}개 / 원격에만 ${diff.remoteOnly.length}개 / 수정 ${diff.changed.length}개. 이름 변경 ${diff.projectChanged?'있음':'없음'}, 창고 규격 변경 ${diff.warehouseChanged?'있음':'없음'}. 로컬 JSON을 백업한 뒤 최신 도면을 여세요. 자동 덮어쓰지 않습니다.`;});
$('ghFiles').onchange=()=>{if($('ghFiles').value)$('ghPath').value=$('ghFiles').value;};
$('ghLoad').onclick=()=>ghRun(async()=>{const s=ghSettings(),file=await api(s.url+'?ref='+encodeURIComponent(s.branch));if(file.size>5_000_000||file.encoding!=='base64')throw Error('지원하지 않는 파일 크기 또는 형식입니다.');const next=normalize(JSON.parse(fromBase64(file.content)));if(confirm('GitHub 도면으로 현재 화면을 바꿀까요?')){replace(next);known.set(s.key,file.sha);$('ghStatus').textContent='도면을 불러왔습니다. 기존 브라우저 도면은 실행 취소로 복구할 수 있습니다.';}});
$('leftToggle').onclick=()=>{$('right').classList.remove('open');$('left').classList.toggle('open');};$('rightToggle').onclick=()=>{$('left').classList.remove('open');$('right').classList.toggle('open');};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.remove('open'));

function makeLabel(text,x,y,z){
 const c=document.createElement('canvas');c.width=512;c.height=96;
 const ctx=c.getContext('2d');ctx.fillStyle='#143448e6';ctx.fillRect(0,0,512,96);
 ctx.fillStyle='#ffffff';ctx.font='bold 34px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text.slice(0,25),256,48,484);
 const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;const material=new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false});
 const sprite=new THREE.Sprite(material);sprite.position.set(x,y,z);sprite.scale.set(2.8,.525,1);labelRoot.add(sprite);
}
function buildShell(){
 shellRoot.traverse(m=>{if(m.userData.ownedMaterial)m.material.dispose();});shellRoot.clear();labelRoot.traverse(o=>{if(o.material){o.material.map?.dispose();o.material.dispose();}});labelRoot.clear();
 const w=layout.warehouse;
 for(const z of [-.1,w.depth+.1])box(shellRoot,w.width+.4,w.height,.18,w.width/2,w.height/2,z,'#d4e0e4');
 for(const x of [-.1,w.width+.1])box(shellRoot,.18,w.height,w.depth,x,w.height/2,w.depth/2,'#d4e0e4');
 box(shellRoot,w.width+.4,.16,w.depth+.4,w.width/2,w.height+.2,w.depth/2,'#dce7e8');
 for(let x=2;x<w.width;x+=6){box(shellRoot,.14,.22,w.depth,x,w.height-.2,w.depth/2,'#5e7e8c');const fixture=box(shellRoot,1.6,.05,.28,x,w.height-.36,w.depth/2,'#ffffff');fixture.material=new THREE.MeshStandardMaterial({color:0xffffff,emissive:0xfff8eb,emissiveIntensity:2});fixture.userData.ownedMaterial=true;
 if(shellRoot.children.filter(c=>c.isLight).length<4){const light=new THREE.PointLight(0xfff5e6,70,Math.max(w.width,w.depth),2);light.position.set(x,w.height-.7,w.depth/2);shellRoot.add(light);}
 for(const z of [-.12,w.depth+.12])box(shellRoot,.22,w.height,.22,x,w.height/2,z,'#83949d');}
 shellRoot.visible=mode==='walk';labelRoot.visible=mode!=='walk';
 layout.objects.filter(o=>['rack','dock','office'].includes(o.type)).slice(0,60).forEach(o=>makeLabel(o.name,o.x,o.z+o.height+.8,o.y));
}
$('focusBtn').onclick=()=>{document.body.classList.toggle('immersive');$('focusBtn').setAttribute('aria-pressed',String(document.body.classList.contains('immersive')));};
$('applySim').onclick=()=>{const speed=Number($('workerSpeed').value),dwell=Number($('workerDwell').value);if(!Number.isFinite(speed)||speed<.2||speed>3||!Number.isFinite(dwell)||dwell<0||dwell>60){toast('속도 0.2~3m/s, 작업 시간 0~60초로 입력하세요.');return;}layout.simulation={speed,dwell};history.push(layout);persist();rebuild();setupSimulation();syncPlayLabels();toast('운영 조건 적용 완료');};
try{const s=JSON.parse(localStorage.getItem('warehouse-city-github'));if(s)for(const [id,key]of Object.entries({ghOwner:'owner',ghRepo:'repo',ghBranch:'branch',ghPath:'path'}))if(typeof s[key]==='string')$(id).value=s[key];}catch{}

let backgroundImage=null,backgroundData='',backgroundPoints=[];
$('backgroundBtn').onclick=()=>$('backgroundFile').click();
$('backgroundFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(!['image/png','image/jpeg'].includes(file.type)||file.size>5000000)throw Error('PNG/JPEG 5MB 이하를 선택하세요.');const bitmap=await createImageBitmap(file),c=document.createElement('canvas'),ratio=Math.min(1,1280/Math.max(bitmap.width,bitmap.height));c.width=Math.round(bitmap.width*ratio);c.height=Math.round(bitmap.height*ratio);c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();backgroundData=c.toDataURL('image/jpeg',.8);if(backgroundData.length>900000)throw Error('압축 후 배경이 너무 큽니다. 더 작은 이미지를 선택하세요.');backgroundImage=c;backgroundPoints=[];const preview=$('backgroundCanvas');preview.width=c.width;preview.height=c.height;preview.getContext('2d').drawImage(c,0,0);$('backgroundDialog').showModal();}catch(err){toast(err.message);}e.target.value='';};
$('backgroundCanvas').onclick=e=>{if(backgroundPoints.length===2)backgroundPoints=[];const c=e.currentTarget,r=c.getBoundingClientRect();backgroundPoints.push({x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height});const ctx=c.getContext('2d');ctx.drawImage(backgroundImage,0,0);for(const p of backgroundPoints){ctx.beginPath();ctx.arc(p.x,p.y,8,0,Math.PI*2);ctx.fillStyle='#ee503b';ctx.fill();}};
$('backgroundApply').onclick=()=>{try{const scale=calibrateBackground(backgroundPoints,Number($('backgroundDistance').value),backgroundImage.width,backgroundImage.height);layout.background={...scale,data:backgroundData,x:layout.warehouse.width/2,y:layout.warehouse.depth/2,opacity:.4,locked:true};commit();$('backgroundDialog').close();}catch(e){toast(e.message);}};
$('backgroundClose').onclick=()=>$('backgroundDialog').close();
$('backgroundOpacity').onchange=()=>{if(layout.background){layout.background.opacity=Number($('backgroundOpacity').value);commit();}};
$('backgroundLocked').onchange=()=>{if(layout.background){layout.background.locked=$('backgroundLocked').checked;commit();}};
$('backgroundPosition').onclick=()=>{if(!layout.background||layout.background.locked){toast('배경 잠금을 해제하세요.');return;}const x=Number($('backgroundX').value),y=Number($('backgroundY').value);if(Number.isFinite(x)&&Number.isFinite(y)){layout.background.x=x;layout.background.y=y;commit();}};
$('multiAll').onclick=()=>{multiSelected.clear();layout.objects.filter(o=>!o.locked&&!['aisle','safety','waypoint'].includes(o.type)).forEach(o=>multiSelected.add(o.id));$('multiCount').textContent=multiSelected.size+'개 선택';};
$('multiClear').onclick=()=>{multiSelected.clear();$('multiCount').textContent='Shift+클릭으로 여러 설비 선택';};
function batchEdit(action){if(mode!=='edit')return;const next=copy(layout),objects=next.objects.filter(o=>multiSelected.has(o.id));if(!objects.length)return;if(objects.some(o=>o.locked)){toast('잠긴 설비가 포함되어 있습니다.');return;}const dx=Number($('multiX').value),dy=Number($('multiY').value);if(![dx,dy].every(Number.isFinite))return;
 if(action==='move')objects.forEach(o=>{o.x+=dx;o.y+=dy;});
 if(action==='alignX')objects.forEach(o=>o.x=objects[0].x);
 if(action==='alignY')objects.forEach(o=>o.y=objects[0].y);
 if(action==='spaceX'&&objects.length>2){objects.sort((a,b)=>a.x-b.x);const start=objects[0].x,end=objects.at(-1).x;objects.forEach((o,i)=>o.x=start+(end-start)*i/(objects.length-1));}
 if(action==='duplicate'){if(next.objects.length+objects.length>MAX_OBJECTS){toast('설비 수 예산 초과');return;}next.objects.push(...objects.map(o=>({...copy(o),id:uid(),x:o.x+dx,y:o.y+dy})));}
 if(action==='delete')next.objects=next.objects.filter(o=>!multiSelected.has(o.id));
 const error=next.objects.find(o=>placementError(o,next));if(error){toast(error.name+' · '+placementError(error,next)+' · 전체 작업을 취소했습니다.');return;}replace(next);multiSelected.clear();$('multiCount').textContent='선택 해제';}
document.querySelectorAll('[data-batch]').forEach(b=>b.onclick=()=>batchEdit(b.dataset.batch));
$('scenarioA').onclick=()=>{scenarioA=copy(layout);$('experimentResult').textContent='A 도면을 기억했습니다. 설계에서 작업자 수나 통로를 바꾼 뒤 비교하세요.';};
$('compareScenarios').onclick=()=>{if(!scenarioA){toast('먼저 A 도면을 기억하세요.');return;}if(experimentWorker)experimentWorker.terminate();experimentWorker=new Worker('./city-experiment-worker.mjs',{type:'module'});$('experimentResult').textContent='동일 시드 5개로 각 600초 계산 중…';experimentWorker.onmessage=({data})=>{$('experimentResult').textContent=data.error||`가정 기반 모의 결과 · 동일 시드 ${data.seeds.join(', ')}\nA 출하 평균 ${data.a.mean.toFixed(1)} (범위 ${data.a.min}~${data.a.max}, 표준편차 ${data.a.std.toFixed(2)})\nB 출하 평균 ${data.b.mean.toFixed(1)} (범위 ${data.b.min}~${data.b.max}, 표준편차 ${data.b.std.toFixed(2)})`;experimentWorker.terminate();experimentWorker=null;};experimentWorker.onerror=()=>{$('experimentResult').textContent='비교 계산 실패. 도면은 변경되지 않았습니다.';experimentWorker.terminate();experimentWorker=null;};experimentWorker.postMessage({a:scenarioA,b:copy(layout)});};
$('minimap').onclick=e=>{if(mode!=='walk')return;const c=e.currentTarget,r=c.getBoundingClientRect(),w=layout.warehouse,s=Math.min((c.width-24)/w.width,(c.height-24)/w.depth),x=((e.clientX-r.left)*c.width/r.width-(c.width-w.width*s)/2)/s,y=((e.clientY-r.top)*c.height/r.height-(c.height-w.depth*s)/2)/s;if(!blocked(x,y,layout)){walk={x,y};}else toast('이 위치는 막혀 있습니다. 통로를 선택하세요.');};
$('qualityDemo').onclick=()=>{if(confirm('현재 도면을 작은 시연 구역으로 바꿀까요? Undo로 복구할 수 있습니다.'))replace(qualityDemo());};
$('operationKind').onchange=()=>{operationKind=$('operationKind').value;rebuild();setupSimulation();syncPlayLabels();};
$('qualityPreset').onchange=()=>{const q=$('qualityPreset').value;for(const g of groups.values())if(g.userData.rackLOD)g.levels[1].distance=q==='low'?12:80;renderer.setPixelRatio(Math.min(devicePixelRatio,q==='high'?2:q==='low'?1:1.5));renderer.shadowMap.enabled=q!=='low';sun.shadow.mapSize.setScalar(q==='high'?2048:1024);sun.shadow.map?.dispose();sun.shadow.map=null;};
$('viewpoint').onchange=()=>{const kind=$('viewpoint').value,source=layout.objects.find(o=>o.type===kind);if(!source)return;const live=sim?.agents.find(a=>a.id===source.id),o=live?{...source,x:live.x,y:live.y}:source;if(mode!=='walk')setMode('walk');const candidates=live?[.7,-.7,1.5,-1.5,0,3.14].map(angle=>({x:o.x+Math.sin((live.heading||0)+angle)*(kind==='forklift'?4:3),y:o.y+Math.cos((live.heading||0)+angle)*(kind==='forklift'?4:3)})):[{x:o.x,y:o.y+o.depth/2+2.8},{x:o.x+o.width/2+2.8,y:o.y},{x:o.x,y:o.y-o.depth/2-2.8}];const p=candidates.find(p=>!blocked(p.x,p.y,layout)&&(!sim||sim.agents.every(a=>Math.hypot(a.x-p.x,a.y-p.y)>2)));if(p){walk=p;yaw=Math.atan2(p.x-o.x,p.y-o.y);pitch=-.05;}};
$('walkFov').oninput=()=>{perspective.fov=Number($('walkFov').value);perspective.updateProjectionMatrix();};
const requestedQuality=new URLSearchParams(location.search).get('quality');if(['low','standard','high'].includes(requestedQuality)){$('qualityPreset').value=requestedQuality;$('qualityPreset').onchange();}
rebuild();iso();catalogue();requestAnimationFrame(animate);document.documentElement.dataset.ready='true';
window.__warehouseCity={version:'9.1.1',getAssets:assetInfo,getCacheStats:cacheStats,getRenderStats:()=>{let meshes=0,instances=0;objectsRoot.traverse(m=>{if(m.isMesh)meshes++;if(m.isInstancedMesh)instances+=m.count;});return {...rackPlan,meshes,instances,frame:renderer.info.render.frame,calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures};},getLogistics:()=>sim instanceof Logistics?{...sim.metrics(),units:copy(sim.units),events:copy(sim.events)}:null,getPlaying:()=>playing,getView:()=>({yaw,pitch,x:camera.position.x,y:camera.position.y,z:camera.position.z}),screenPoint:(x,y,z=0)=>{const p=new THREE.Vector3(x,z,y).project(camera),r=canvas.getBoundingClientRect();return {x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2};},getLayout:()=>copy(layout),getMode:()=>mode,getSimulation:()=>sim?{time:sim.time,arrivals:sim.arrivals,distance:sim.distance,agents:sim.agents.map(a=>({x:a.x,y:a.y,status:a.status}))}:null,getWalk:()=>({...walk}),setMode};
if(loadWarning)toast(loadWarning);

