import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=process.env.BASE_URL||'http://127.0.0.1:4173/';
const dir=process.env.QA_DIR||'qa-evidence';await fs.mkdir(dir,{recursive:true});
const results=[],errors=[];
const browser=await chromium.launch({args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'ko-KR'});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
const state=()=>page.evaluate(()=>window.__warehouseCity.getLayout());
const ready=async p=>{await p.waitForFunction(()=>document.documentElement.dataset.ready==='true');await p.waitForTimeout(250);};
const check=async(name,fn)=>{try{await fn();results.push({name,passed:true});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:e.message});await page.screenshot({path:`${dir}/failure.png`}).catch(()=>{});throw e;}};
async function place(type,x,y){await page.locator('.asset').filter({hasText:type}).click();const p=await page.evaluate(([x,y])=>window.__warehouseCity.screenPoint(x,y),[x,y]);await page.mouse.click(p.x,p.y);await page.waitForTimeout(100);}
try{
 await check('default entry renders real WebGL',async()=>{await page.goto(base);await ready(page);assert.equal(await page.evaluate(()=>window.__warehouseCity.version),'9.1.0');assert.ok((await state()).objects.length>20);assert.equal(await page.locator('#fatal').isVisible(),false);await page.screenshot({path:`${dir}/desktop-design.png`});});
 await check('new blank warehouse, real pointer placement and rotation',async()=>{await page.locator('#blankBtn').click();assert.equal((await state()).objects.length,0);await page.locator('#topBtn').click();await page.waitForTimeout(350);await place('팔레트 랙',10,10);assert.equal((await state()).objects.length,1);await page.keyboard.press('Escape');await page.mouse.click(...Object.values(await page.evaluate(()=>window.__warehouseCity.screenPoint(10,10,3))));await page.locator('#rotateBtn').click();assert.equal((await state()).objects[0].rotation,90);});
 await check('inspector changes rack capacity and colour',async()=>{await page.locator('#rackBays').fill('3');await page.locator('#rackLevels').fill('5');await page.locator('#objectColor').fill('#336699');await page.locator('#applyObject').click();const o=(await state()).objects[0];assert.equal(o.config.bays,3);assert.equal(o.config.levels,5);assert.equal(o.color,'#336699');});
 await check('undo and redo preserve object properties',async()=>{await page.locator('#undoBtn').click();assert.equal((await state()).objects[0].config.bays,4);await page.locator('#redoBtn').click();assert.equal((await state()).objects[0].config.bays,3);});
 await check('row placement is atomic, including invalid overlap',async()=>{await page.locator('#blankBtn').click();await page.locator('#rowBtn').click();await page.locator('#rowApply').click();assert.equal((await state()).objects.length,3);await page.locator('#rowBtn').click();await page.locator('#rowApply').click();assert.equal((await state()).objects.length,3);assert.equal(await page.locator('#rowDialog').isVisible(),true);await page.locator('#rowClose').click();});
 await check('Korean project name survives automatic save and reload',async()=>{await page.locator('#projectName').fill('한글 물류센터 검증');await page.locator('#projectName').blur();await page.waitForTimeout(400);await page.reload();await ready(page);assert.equal((await state()).projectName,'한글 물류센터 검증');assert.equal((await state()).objects.length,3);});
 await check('JSON export and import round trip',async()=>{const expected=await state();const event=page.waitForEvent('download');await page.locator('#exportBtn').click();const download=await event;const path=`${dir}/export-roundtrip.json`;await download.saveAs(path);assert.deepEqual(JSON.parse(await fs.readFile(path,'utf8')),expected);await page.locator('#blankBtn').click();await page.locator('#importFile').setInputFiles(path);await page.waitForFunction(name=>window.__warehouseCity.getLayout().projectName===name,expected.projectName);assert.deepEqual(await state(),expected);});
 await check('legacy JSON loads without overwriting legacy browser data',async()=>{const text=await fs.readFile('layouts/standard-distribution-center.json','utf8');await page.evaluate(t=>localStorage.setItem('warehouse-studio-project-v1',t),text);await page.locator('#legacyImport').click();assert.ok((await state()).objects.length>0);assert.equal(await page.evaluate(()=>localStorage.getItem('warehouse-studio-project-v1')),text);});
 await check('workers move, pause and preserve original design positions',async()=>{await page.locator('#demoBtn').click();const original=await state();await page.locator('[data-mode="sim"]').click();await page.locator('#runBtn').click();await page.waitForFunction(()=>window.__warehouseCity.getSimulation()?.distance>1);assert.deepEqual(await state(),original);await page.locator('#runBtn').click();const before=await page.evaluate(()=>window.__warehouseCity.getSimulation().time);await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>window.__warehouseCity.getSimulation().time),before);await page.screenshot({path:`${dir}/desktop-simulation.png`});});
 await check('simulation speed and dwell are editable and reset the run',async()=>{await page.locator('#workerSpeed').fill('2');await page.locator('#workerDwell').fill('3');await page.locator('#applySim').click();assert.deepEqual((await state()).simulation,{speed:2,dwell:3});assert.equal(await page.evaluate(()=>window.__warehouseCity.getSimulation().time),0);});
 await check('walkthrough keeps workers running and WASD moves the camera',async()=>{await page.locator('#runBtn').click();await page.locator('[data-mode="walk"]').click();const before=await page.evaluate(()=>({walk:window.__warehouseCity.getWalk(),distance:window.__warehouseCity.getSimulation().distance}));await page.locator('#scene').focus();await page.keyboard.down('KeyW');await page.waitForTimeout(700);await page.keyboard.up('KeyW');const after=await page.evaluate(()=>({walk:window.__warehouseCity.getWalk(),distance:window.__warehouseCity.getSimulation().distance}));assert.ok(after.distance>before.distance);assert.ok(after.walk.y<before.walk.y);await page.screenshot({path:`${dir}/desktop-walk.png`});});
 await check('first-person drag look and focus mode work',async()=>{const c=await page.locator('#scene').boundingBox(),before=await page.evaluate(()=>window.__warehouseCity.getView().yaw);await page.mouse.move(c.x+c.width/2,c.y+c.height/2);await page.mouse.down();await page.mouse.move(c.x+c.width/2+100,c.y+c.height/2);await page.mouse.up();assert.notEqual(await page.evaluate(()=>window.__warehouseCity.getView().yaw),before);await page.locator('#focusBtn').click();assert.equal(await page.locator('#left').isVisible(),false);await page.locator('#focusBtn').click();await page.locator('[data-mode="edit"]').click();});
 await check('walk camera cannot pass through a thin wall',async()=>{const fixture={warehouse:{width:20,depth:20,height:8},objects:[{id:'wall',type:'partition',x:10,y:4,width:19,depth:.18,height:3},{id:'worker',type:'worker',x:10,y:5}]};await page.locator('#importFile').setInputFiles({name:'wall.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});await page.waitForFunction(()=>window.__warehouseCity.getLayout().objects.some(o=>o.id==='wall'));await page.locator('[data-mode="walk"]').click();await page.locator('#scene').focus();await page.keyboard.down('KeyW');await page.waitForTimeout(1200);await page.keyboard.up('KeyW');assert.ok((await page.evaluate(()=>window.__warehouseCity.getWalk())).y>=4.38);await page.locator('[data-mode="edit"]').click();await page.locator('#demoBtn').click();});
 // Mock GitHub's documented Contents API to test write races and credential hygiene.
 let remote=null,puts=0,forceStatus=0;const requests=[];
 await page.route('https://api.github.com/repos/**',async route=>{const req=route.request(),url=new URL(req.url()),headers={'access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type,accept,x-github-api-version','access-control-allow-methods':'GET,PUT,OPTIONS'};const reply=(status,obj)=>route.fulfill({status,headers,contentType:'application/json',body:JSON.stringify(obj)});if(req.method()==='OPTIONS')return reply(200,{});if(forceStatus)return reply(forceStatus,{message:'test error'});if(req.method()==='PUT'){puts++;const body=req.postDataJSON();requests.push(body);remote={type:'file',path:'layouts/my-warehouse.json',name:'my-warehouse.json',sha:'mock-sha-'+puts,encoding:'base64',content:body.content,size:Buffer.from(body.content,'base64').length};return reply(puts===1?201:200,{content:{sha:remote.sha},commit:{sha:('abcd'+puts).padEnd(40,'0')}});}if(url.pathname.endsWith('/contents/layouts'))return reply(200,remote?[remote]:[]);return remote?reply(200,remote):reply(404,{message:'Not Found'});});
 const openGit=async()=>{await page.locator('#githubBtn').click();await page.locator('#ghToken').fill('test-token-never-persist');await page.locator('#ghConsent').check();};
 const saved=async()=>page.waitForFunction(()=>document.getElementById('ghStatus').textContent.includes('커밋 완료:'));
 await check('GitHub create commits Korean JSON using no backend',async()=>{await openGit();await page.locator('#ghSave').click();await saved();assert.equal(puts,1);assert.equal(requests[0].sha,undefined);assert.deepEqual(JSON.parse(Buffer.from(requests[0].content,'base64').toString('utf8')),await state());});
 await check('GitHub update uses existing SHA rather than blindly overwriting',async()=>{await page.locator('#ghSave').click();await saved();assert.equal(puts,2);assert.equal(requests[1].sha,'mock-sha-1');});
 await check('remote changes block stale writes',async()=>{remote.sha='changed-elsewhere';await page.locator('#ghSave').click();await page.waitForFunction(()=>document.getElementById('ghStatus').textContent.includes('다른 사용자가'));assert.equal(puts,2);remote.sha='mock-sha-2';});
 await check('401 and 409 responses report errors without losing local work',async()=>{const before=await state();for(const status of [401,409]){forceStatus=status;await page.locator('#ghSave').click();await page.waitForFunction(()=>!document.getElementById('ghSave').disabled);assert.ok((await page.locator('#ghStatus').textContent()).match(/권한|충돌/));}forceStatus=0;assert.deepEqual(await state(),before);});
 await check('GitHub list and load restore the committed document',async()=>{await page.locator('#ghList').click();await page.waitForFunction(()=>document.getElementById('ghFiles').options.length===2);await page.locator('#ghFiles').selectOption('layouts/my-warehouse.json');await page.locator('#ghLoad').click();await page.waitForFunction(()=>document.getElementById('ghStatus').textContent.includes('불러왔습니다'));assert.deepEqual(await state(),JSON.parse(Buffer.from(remote.content,'base64').toString('utf8')));});
 await check('token never enters storage or exported data and clears on close',async()=>{assert.equal(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}).includes('test-token-never-persist')),false);assert.equal(JSON.stringify(await state()).includes('test-token-never-persist'),false);await page.locator('#ghClose').click();assert.equal(await page.locator('#ghToken').inputValue(),'');assert.equal(await page.locator('#ghConsent').isChecked(),false);});
 await check('mobile layout, touch navigation and GitHub dialog',async()=>{const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1,locale:'ko-KR'});const p=await mobile.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await ready(p);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`${dir}/mobile-design.png`});await p.locator('#leftToggle').click();assert.equal(await p.locator('#left').isVisible(),true);await p.locator('[data-close="left"]').click();await p.locator('[data-mode="sim"]').click();await p.locator('#runBtn').click();await p.waitForFunction(()=>window.__warehouseCity.getSimulation()?.distance>.1);await p.locator('[data-mode="walk"]').click();const before=await p.evaluate(()=>window.__warehouseCity.getWalk());const r=await p.locator('[data-key="KeyW"]').boundingBox(),cdp=await mobile.newCDPSession(p);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x+r.width/2,y:r.y+r.height/2}]});await p.waitForTimeout(600);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok((await p.evaluate(()=>window.__warehouseCity.getWalk())).y<before.y);await p.screenshot({path:`${dir}/mobile-walk.png`});await p.locator('#githubBtn').click();assert.equal(await p.locator('#githubDialog').isVisible(),true);await p.locator('#ghClose').click();await mobile.close();});
 await check('classic editor remains accessible with its original assets',async()=>{const classic=await context.newPage();const errs=[];classic.on('pageerror',e=>errs.push(e.message));await classic.goto(new URL('classic.html',base).href);await classic.waitForTimeout(1500);assert.ok((await classic.title()).includes('Warehouse Studio'));assert.deepEqual(errs,[]);await classic.close();});
 await check('no unhandled browser exceptions',async()=>assert.deepEqual(errors,[]));
} finally {await fs.writeFile(`${dir}/browser-results.json`,JSON.stringify({passed:results.every(r=>r.passed),total:results.length,results,errors},null,2));await browser.close();}
