import {chromium} from 'playwright';
import fs from 'node:fs/promises';
const dir='qa-evidence/renewal';await fs.mkdir(dir,{recursive:true});
const browser=await chromium.launch({channel:'msedge'});
const context=await browser.newContext({viewport:{width:1440,height:900},recordVideo:{dir:dir+'/video',size:{width:1440,height:900}}});
const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());
await p.goto('http://127.0.0.1:4173');await p.waitForFunction(()=>window.__warehouseCity);
await p.locator('#qualityDemo').click();await p.screenshot({path:dir+'/overview.png'});
await p.locator('#topBtn').click();await p.screenshot({path:dir+'/plan.png'});await p.locator('#isoBtn').click();
await p.locator('[data-mode="sim"]').click();await p.locator('#operationKind').selectOption('tasks');await p.locator('#runBtn').click();await p.waitForTimeout(2000);
await p.locator('[data-mode="walk"]').click();await p.screenshot({path:dir+'/interior.png'});
await p.locator('#scene').focus();await p.keyboard.down('KeyW');await p.waitForTimeout(1200);await p.keyboard.up('KeyW');await p.screenshot({path:dir+'/walk.png'});
await fs.writeFile(dir+'/report.json',JSON.stringify({errors,assets:await p.evaluate(()=>window.__warehouseCity.getAssets()),render:await p.evaluate(()=>window.__warehouseCity.getRenderStats()),simulation:await p.evaluate(()=>window.__warehouseCity.getLogistics())},null,2));
await context.close();await browser.close();if(errors.length)throw Error(errors.join('\n'));
