import test from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs';import {GitHubStore,validTarget,validFile,encodeUTF8,decodeUTF8} from '../studio-github.js';
const response=(status,data)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
const project={projectName:'한글 창고 🏭',objects:[]};
function mock(sequence){const requests=[];return {requests,fetch:async(url,opts)=>{requests.push({url,...opts});const r=sequence.shift();if(!r)throw new Error('unexpected request');if(r instanceof Error)throw r;return response(r[0],r[1]);}};}
test('UTF8 base64 roundtrip preserves Korean and emoji',()=>assert.equal(decodeUTF8(encodeUTF8(JSON.stringify(project))),JSON.stringify(project)));
test('file paths reject traversal, reserved folders and query injection',()=>{for(const s of ['../secret','.github/workflows/a','a?x=1','a/b','a%2fb','..',''])assert.throws(()=>validFile(s));assert.equal(validFile('인천-창고_1.json'),'인천-창고_1.json');});
test('repository target always remains api.github.com and validates branch',()=>{assert.throws(()=>validTarget({owner:'evil.com/a',repo:'x'}));assert.throws(()=>validTarget({owner:'abc',repo:'../x'}));assert.throws(()=>validTarget({branch:'../main'}));assert.equal(validTarget().repo,'3D_warehouse');});
test('new file probes absence then creates commit, with no credentials in JSON',async()=>{const m=mock([[404,{}],[201,{content:{sha:'newsha'},commit:{sha:'commit1'}}]]),g=new GitHubStore({},'mock-only-credential',m.fetch);const saved=await g.save('first',project);assert.equal(saved.sha,'newsha');assert.equal(m.requests.length,2);const body=JSON.parse(m.requests[1].body);assert.equal(body.sha,undefined);assert.equal(decodeUTF8(body.content),JSON.stringify(project,null,2));assert.equal(body.branch,'main');assert(!m.requests[1].body.includes('mock-only-credential'));});
test('loaded file updates with originally loaded SHA, not freshly fetched SHA',async()=>{const m=mock([[200,{content:encodeUTF8(JSON.stringify(project)),sha:'loaded-sha',encoding:'base64',size:80}],[200,{content:{sha:'updated-sha'}}]]),g=new GitHubStore({},'mock-only-credential',m.fetch);await g.load('x');await g.save('x',project);assert.equal(m.requests.length,2);assert.equal(JSON.parse(m.requests[1].body).sha,'loaded-sha');});
test('existing but never loaded file cannot be silently overwritten',async()=>{const m=mock([[200,{sha:'someone-else'}]]),g=new GitHubStore({},'mock-only-credential',m.fetch);await assert.rejects(g.save('existing',project),e=>e.status===409);assert.equal(m.requests.length,1);});
for(const status of [401,403,404,409,422,429,500])test(`GitHub HTTP ${status} is surfaced and never marked saved`,async()=>{const m=mock([[status,{}]]),g=new GitHubStore({},'mock-only-credential',m.fetch);await assert.rejects(g.load('x'),e=>e.status===status);});
test('409 update conflict retains loaded SHA and caller data',async()=>{const m=mock([[200,{content:encodeUTF8(JSON.stringify(project)),sha:'original',encoding:'base64',size:90}],[409,{}],[200,{content:{sha:'retry'}}]]),g=new GitHubStore({},'mock-only-credential',m.fetch);await g.load('x');const snap=JSON.stringify(project);await assert.rejects(g.save('x',project),e=>e.status===409);assert.equal(JSON.stringify(project),snap);await g.save('x',project);assert.equal(JSON.parse(m.requests[2].body).sha,'original');});
test('without token public read works but writes rejected before fetch',async()=>{const m=mock([[200,[]]]),g=new GitHubStore({},'',m.fetch);await g.list();assert(!m.requests[0].headers.Authorization);await assert.rejects(g.save('x',project),e=>e.status===401);assert.equal(m.requests.length,1);});
test('network failure reports a recoverable error',async()=>{const m=mock([new Error('offline')]),g=new GitHubStore({},'',m.fetch);await assert.rejects(g.list(),e=>e.status===0);});
test('share URL never includes token, old queries or fragment; read-only route',()=>{const g=new GitHubStore({},'mock-only-credential');const url=g.shareURL('x','https://dalmook.github.io/3D_warehouse/?token=old#private');assert(!url.includes('token'));assert(!url.includes('private'));assert(!url.includes('mock-only'));assert.equal(new URL(url).searchParams.get('mode'),'walk');});
test('disconnect erases credential and loaded SHA; secrets are not serializable/persisted',async()=>{const m=mock([]),g=new GitHubStore({},'mock-only-credential',m.fetch);assert(!JSON.stringify(g).includes('mock-only-credential'));g.disconnect();assert.equal(g.connected,false);await assert.rejects(g.save('x',project));const source=fs.readFileSync(new URL('../studio-github.js',import.meta.url),'utf8');assert(!source.includes('localStorage'));assert(!source.includes('sessionStorage'));assert(!source.includes('console.'));});
test('concurrent save is serialized and duplicate click rejected',async()=>{let release;let calls=0;const g=new GitHubStore({},'mock-only-credential',async()=>{calls++;if(calls===1)return new Promise(r=>release=()=>r(response(404,{})));return response(201,{content:{sha:'done'}});});const first=g.save('x',project);await assert.rejects(g.save('x',project),e=>e.status===409);release();await first;assert.equal(calls,2);});
