import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {normalize,object} from '../city-core.mjs';
import {stackLayout} from '../city-domain.mjs';
const dir=process.env.QA_DIR||'qa-evidence/practical';await fs.mkdir(dir,{recursive:true});
const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||undefined,args:process.env.BROWSER_CHANNEL?[]:['--use-angle=swiftshader','--enable-unsafe-swiftshader']}),context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
const base=process.env.BASE_URL||'http://127.0.0.1:4173/';
const state=()=>page.evaluate(()=>window.__warehouseCity.getLayout());
async function load(layout){await page.locator('#importFile').setInputFiles({name:'synthetic.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(layout))});await page.waitForFunction(name=>window.__warehouseCity.getLayout().projectName===name,layout.projectName);}
async function select(id){await page.locator('#toolsButton').click();await page.locator('#objectList').selectOption(id);}
async function close(id){await page.locator('#'+id+' [data-dismiss]').click();}
try{
 await page.goto(base);await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');
 const l=normalize({projectName:'실무 기능 검증',warehouse:{width:36,depth:24,height:9},objects:[object('pallet',4,5,{id:'pallet',height:.14}),object('sign',9,5,{id:'sign',config:{text:'입고 대기'},z:1.5}),object('rack',18,10,{id:'rack',rotation:45,config:{bays:30,levels:4,palletsPerLevel:2}}),object('worker',2,10,{id:'worker'}),object('waypoint',3,10)]});await load(l);
 await select('pallet');await page.locator('#selectedStack').click();await page.locator('#stackPreview').click();assert.match(await page.locator('#stackResult').innerText(),/1640mm/);await page.locator('#stackApply').click();assert.equal((await state()).objects.find(o=>o.id==='pallet').load.actual,48);
 await page.getByText('포함 박스 편집',{exact:true}).click();const lastBox=await page.locator('#loadBox option').last().getAttribute('value');await page.locator('#loadBox').selectOption(lastBox);await page.locator('#removeLoadBox').click();assert.equal((await state()).objects.find(o=>o.id==='pallet').load.actual,47);await page.locator('#addLoadBox').click();assert.equal((await state()).objects.find(o=>o.id==='pallet').load.actual,48);
 await page.locator('#topBtn').click();await page.locator('#dimensionButton').click();await page.locator('#dimensionMode').selectOption('measure');await close('dimensionDialog');for(const x of [12,15]){const q=await page.evaluate(x=>window.__warehouseCity.screenPoint(x,18),x);await page.mouse.click(q.x,q.y);}assert.equal((await state()).measurements.length,1);
 await page.locator('#themeSelect').selectOption('blueprint');await page.locator('#dimensionButton').click();await page.locator('#dimensionMode').selectOption('all');await close('dimensionDialog');await page.locator('#topBtn').click();await page.waitForTimeout(300);await page.screenshot({path:dir+'/blueprint.png'});
 const colors=(await state()).objects.map(o=>o.color);await page.locator('[data-mode="sim"]').click();await page.locator('[data-mode="walk"]').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'blueprint');assert.deepEqual((await state()).objects.map(o=>o.color),colors);await page.locator('[data-mode="edit"]').click();
 await select('pallet');await page.locator('#scene').focus();await page.keyboard.press('Control+c');await page.keyboard.press('Control+v');const p=await page.evaluate(()=>window.__warehouseCity.screenPoint(8,16));await page.mouse.move(p.x,p.y);await page.keyboard.press('Enter');assert.equal((await state()).objects.filter(o=>o.load).length,2);await page.locator('#undoBtn').click();assert.equal((await state()).objects.filter(o=>o.load).length,1);await page.locator('#redoBtn').click();assert.equal((await state()).objects.filter(o=>o.load).length,2);
 await select('sign');await page.locator('#equipmentText').fill('출하 검사');await page.locator('#extraApply').click();await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');assert.equal((await state()).objects.find(o=>o.id==='sign').config.text,'출하 검사');assert.equal((await state()).objects.find(o=>o.id==='rack').config.bays,30);assert.equal(await page.locator('html').getAttribute('data-theme'),'blueprint');
 await page.locator('#downloadDrawing').click();await page.locator('#outputScale').selectOption('200');await page.locator('#outputAuthor').fill('합성 검수');for(const ext of ['DXF','SVG','PNG','PDF','JSON']){const promise=page.waitForEvent('download');await page.locator('#output'+ext).click();const download=await promise;await download.saveAs(`${dir}/example.${ext.toLowerCase()}`);}await close('drawingDialog');
 const pageCount=await page.evaluate(async()=>{const {CATALOG,object,normalize}=await import('./city-core.mjs'),{reportPDF}=await import('./city-output.mjs');const l=normalize({warehouse:{width:36,depth:24,height:9},objects:Object.keys(CATALOG).map((t,i)=>object(t,3+i%6*5,3+Math.floor(i/6)*3))});const text=await(await reportPDF(l,{paper:'A4',scale:200})).text();return Number(text.match(/\/Count (\d+)/)[1]);});assert.ok(pageCount>=4,'A4 quantity table paginates all catalogue types');
 await page.locator('#sharedSave').click();await page.locator('#sharedDialog summary').click();await page.locator('#sharedOwner').fill('example');await page.locator('#sharedRepo').fill('approved-layouts');await page.locator('#sharedApproved').check();await page.locator('#sharedConfigure').click();const event=page.waitForEvent('download');await page.locator('#sharedPrepare').click();await (await event).saveAs(dir+'/shared-prepared.json');const url=await page.locator('#sharedUpload').getAttribute('href');assert.equal(url,'https://github.com/example/approved-layouts/upload/main/layouts');assert.match(await page.locator('#sharedStatus').innerText(),/미저장/);await close('sharedDialog');
 await page.locator('#themeSelect').selectOption('light');await page.locator('#isoBtn').click();await page.screenshot({path:dir+'/light.png'});
 await context.close();const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const p2=await mobile.newPage();await p2.goto(base);await p2.waitForFunction(()=>document.documentElement.dataset.ready==='true');await p2.locator('#themeSelect').selectOption('dark');await p2.locator('#downloadDrawing').click();assert.ok(await p2.locator('#outputDXF').isVisible());await p2.screenshot({path:dir+'/mobile-download.png'});await mobile.close();assert.deepEqual(errors,[]);console.log('PRACTICAL PASS stack/theme/clipboard/legacy text/30 bays/downloads/shared preparation/mobile');
}finally{await browser.close();}
