import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const dir='qa-evidence/final';await fs.mkdir(dir,{recursive:true});
const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge'});
const context=await browser.newContext({viewport:{width:1440,height:900},recordVideo:{dir:dir+'/video',size:{width:1440,height:900}},deviceScaleFactor:1});
const p=await context.newPage(),errors=[],results=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text());});p.on('dialog',d=>d.accept());
const check=async(name,fn)=>{await fn();results.push({name,passed:true});console.log('RENEWAL PASS',name);};
await p.goto('http://127.0.0.1:4173');await p.waitForFunction(()=>window.__warehouseCity);
await p.locator('#qualityDemo').click();await p.locator('#left').evaluate(e=>e.scrollTop=0);
await check('actual assets and independent skeletons',async()=>{
 const report=await p.evaluate(async()=>{const {fitAsset,releaseInstance}=await import('./city-assets.mjs');const a=fitAsset('worker',{width:.6,depth:.6,height:1.8}),b=fitAsset('worker',{width:.6,depth:.6,height:1.8});let sa,sb;a.traverse(m=>{if(m.isSkinnedMesh)sa=m.skeleton;});b.traverse(m=>{if(m.isSkinnedMesh)sb=m.skeleton;});const independent=sa!==sb&&sa.bones.every((x,i)=>x!==sb.bones[i]);releaseInstance(a);releaseInstance(b);return {independent,assets:window.__warehouseCity.getAssets()};});assert.ok(report.independent);assert.equal(report.assets.length,11);assert.equal(report.assets.find(a=>a.id==='worker').clips.length,4);
});
await p.screenshot({path:dir+'/overview-1440.png'});
await p.locator('#topBtn').click();await p.screenshot({path:dir+'/plan.png'});await p.locator('#isoBtn').click();
await check('background image calibration persists and round trips',async()=>{
 await p.locator('#backgroundFile').setInputFiles('assets/textures/epoxy-albedo.png');await p.locator('#backgroundDialog').waitFor({state:'visible'});const c=await p.locator('#backgroundCanvas').boundingBox();await p.mouse.click(c.x+c.width*.2,c.y+c.height*.5);await p.mouse.click(c.x+c.width*.8,c.y+c.height*.5);await p.locator('#backgroundDistance').fill('10');await p.locator('#backgroundApply').click();const a=await p.evaluate(()=>window.__warehouseCity.getLayout().background);assert.ok(a.width>16&&a.width<17);await p.reload();await p.waitForFunction(()=>window.__warehouseCity);assert.deepEqual(await p.evaluate(()=>window.__warehouseCity.getLayout().background),a);await p.locator('#qualityDemo').click();
});
await check('rack preview rejects collisions atomically',async()=>{await p.locator('#rowBtn').click();await p.locator('#rowX').fill('6');await p.locator('#rowY').fill('6');await p.locator('#rowCount').fill('1');await p.locator('#rowPreview').click();assert.match(await p.locator('#rowSummary').innerText(),/겹칩니다/);const n=await p.evaluate(()=>window.__warehouseCity.getLayout().objects.length);await p.locator('#rowApply').click();assert.equal(await p.evaluate(()=>window.__warehouseCity.getLayout().objects.length),n);await p.locator('#rowClose').click();});
await p.locator('[data-mode="sim"]').click();await p.locator('#operationKind').selectOption('tasks');await p.locator('#simSpeed').selectOption('4');await p.locator('#runBtn').click();
await p.waitForFunction(()=>window.__warehouseCity.getLogistics()?.units.some(u=>u.state==='transport'));
await p.locator('#runBtn').click();await p.locator('[data-mode="walk"]').click();await p.locator('#walkFov').fill('70');await p.locator('#walkFov').dispatchEvent('input');await p.waitForTimeout(4500);
for(const [kind,name] of [['rack','rack-interior'],['dock','dock'],['worker','worker-close'],['forklift','forklift-transport']]){await p.locator('#viewpoint').selectOption(kind);await p.waitForTimeout(200);await p.screenshot({path:dir+'/'+name+'.png'});}
await p.locator('#runBtn').click();await check('operations survive camera mode changes and conserve all units',async()=>{const a=await p.evaluate(()=>window.__warehouseCity.getLogistics());assert.ok(a.conservation.valid);await p.locator('[data-mode="sim"]').click();const b=await p.evaluate(()=>window.__warehouseCity.getLogistics());assert.ok(b.time>=a.time);assert.ok(b.events.length>=a.events.length);});
await p.locator('[data-mode="walk"]').click();await p.locator('#viewpoint').selectOption('rack');await p.locator('#scene').focus();await p.keyboard.down('KeyA');await p.waitForTimeout(1500);await p.keyboard.up('KeyA');
await p.setViewportSize({width:1920,height:1080});await p.locator('[data-mode="edit"]').click();await p.locator('#isoBtn').click();await p.screenshot({path:dir+'/overview-1920.png'});
const performanceReport=await p.evaluate(async()=>{const frames=[];let last=performance.now();await new Promise(resolve=>{function frame(now){frames.push(now-last);last=now;if(frames.length<180)requestAnimationFrame(frame);else resolve();}requestAnimationFrame(frame);});frames.shift();frames.sort((a,b)=>a-b);const gl=document.querySelector('#scene').getContext('webgl2'),debug=gl.getExtension('WEBGL_debug_renderer_info');return {browser:navigator.userAgent,gpu:debug?gl.getParameter(debug.UNMASKED_RENDERER_WEBGL):'unavailable',viewport:{width:innerWidth,height:innerHeight},dpr:devicePixelRatio,preset:document.querySelector('#qualityPreset').value,objects:window.__warehouseCity.getLayout().objects.length,medianMs:frames[Math.floor(frames.length/2)],p99Ms:frames[Math.floor(frames.length*.99)],medianFps:1000/frames[Math.floor(frames.length/2)],onePercentLowFps:1000/frames[Math.floor(frames.length*.99)],render:window.__warehouseCity.getRenderStats(),transferBytes:performance.getEntriesByType('resource').reduce((n,r)=>n+r.transferSize,0),gpuMemory:'not measured'};});
const before=await p.evaluate(()=>window.__warehouseCity.getCacheStats());for(let i=0;i<4;i++){await p.locator('#qualityDemo').click();await p.locator('[data-mode="sim"]').click();await p.locator('[data-mode="walk"]').click();await p.locator('[data-mode="edit"]').click();}const after=await p.evaluate(()=>window.__warehouseCity.getCacheStats());assert.ok(after.mixers<=before.mixers+3);
await fs.writeFile(dir+'/performance.json',JSON.stringify(performanceReport,null,2));
await context.close(); // Desktop and phone represent separate devices; release the first GPU context.
const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});const m=await mobile.newPage();m.on('dialog',d=>d.accept());await m.goto('http://127.0.0.1:4173');await m.waitForFunction(()=>window.__warehouseCity);await m.locator('#leftToggle').click();await m.locator('#qualityDemo').click();await m.locator('[data-close="left"]').click();await m.screenshot({path:dir+'/mobile.png'});await m.locator('[data-mode="walk"]').click();
await check('mobile simultaneous movement and look pointers',async()=>{const c=await m.locator('#scene').boundingBox(),pad=await m.locator('[data-key="KeyW"]').boundingBox(),cdp=await mobile.newCDPSession(m),before=await m.evaluate(()=>({w:window.__warehouseCity.getWalk(),v:window.__warehouseCity.getView()}));const points=[{id:1,x:pad.x+22,y:pad.y+22},{id:2,x:c.x+c.width*.7,y:c.y+c.height*.4}];await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points});points[1].x+=35;await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:points});await m.waitForTimeout(500);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const after=await m.evaluate(()=>({w:window.__warehouseCity.getWalk(),v:window.__warehouseCity.getView()}));assert.notEqual(before.w.y,after.w.y);assert.notEqual(before.v.yaw,after.v.yaw);});
await mobile.close();await fs.writeFile(dir+'/browser.json',JSON.stringify({results,errors,resourceCycles:{before,after}},null,2));await context.close();await browser.close();assert.deepEqual(errors,[]);
